const FETCH_STARTED_ORDER_LIST = 'FETCH_STARTED_ORDER_LIST';
const FETCH_SECCESS_ORDER_LIST = 'FETCH_SECCESS_ORDER_LIST';
const FETCH_FAILURI_ORDER_LIST = 'FETCH_FAILURI_ORDER_LIST';

const COMMENT_ADD = 'COMMENT_ADD';
const COMMENT_CANCEL = 'COMMENT_CANCEL';
const COMMENT_UPDATA = 'COMMENT_UPDATA';

export {
    FETCH_STARTED_ORDER_LIST,
    FETCH_SECCESS_ORDER_LIST,
    FETCH_FAILURI_ORDER_LIST,
    COMMENT_ADD,
    COMMENT_CANCEL,
    COMMENT_UPDATA
}