const FETCH_STARTED_DETAIL_COMMENT = 'FETCH_STARTED_DETAIL_COMMENT';
const FETCH_SECCESS_DETAIL_COMMENT = 'FETCH_SECCESS_DETAIL_COMMENT';
const FETCH_FAILURI_DETAIL_COMMENT = 'FETCH_FAILURI_DETAIL_COMMENT';
const FETCH_INITED_DETAIL_COMMENT = 'FETCH_INITED_DETAIL_COMMENT';

export {
    FETCH_STARTED_DETAIL_COMMENT,
    FETCH_SECCESS_DETAIL_COMMENT,
    FETCH_FAILURI_DETAIL_COMMENT,
    FETCH_INITED_DETAIL_COMMENT
}