const FETCH_STARTED_DETAIL='FETCH_STARTED_DETAIL';
const FETCH_SECCESS_DETAIL='FETCH_SECCESS_DETAIL';
const FETCH_FAILURI_DETAIL='FETCH_FAILURI_DETAIL';

export {FETCH_STARTED_DETAIL,FETCH_SECCESS_DETAIL,FETCH_FAILURI_DETAIL}